repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff
        args: [--fix]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint src
        language: system
        types: [python]
        pass_filenames: false